name: eo-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - xarray
  - zarr
  - s3fs
  - dask
  - numpy
  - pandas
  - matplotlib
  - gdal
  - rasterio
  - rioxarray
  - pyproj
  - affine
  - requests
  - pip
  - pip:
      - minio
      - ypy-websocket
