name: full-eo-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - jupyterhub
  - jupyter-server
  - jupyterlab-server
  - jupyter-ydoc
  - jupyterlab-widgets
  - ipywidgets
  - ipyleaflet
  - ipyurl
  - xarray
  - xarray-leaflet
  - zarr
  - s3fs
  - fsspec
  - dask
  - distributed
  - numpy
  - pandas
  - scipy
  - matplotlib
  - gdal
  - rasterio
  - rioxarray
  - pyproj
  - affine
  - mercantile
  - snuggs
  - xyzservices
  - requests
  - aiohttp
  - aiofiles
  - aiosqlite
  - aiobotocore
  - botocore
  - minio
  - PyJWT
  - pycurl
  - pyopenssl
  - cryptography
  - pamela
  - oauthlib
  - oauthenticator
  - traittypes
  - tqdm
  - pip
  - pip:
      - ypy-websocket
