[bibliography]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

[NOTE]
====
References follow the Springer LNCS citation style. DOIs and persistent URLs are provided where applicable.
====

* [[[ZarrV2, Zarr Specification v2]]],
Miles, A., et al.: _Zarr Specification Version 2_. Zarr Developers. https://zarr.readthedocs.io/en/stable/spec/v2.html

* [[[ZarrV3, Zarr Specification v3]]],
Zarr Community: _Zarr Specification Version 3_. https://zarr-specs.readthedocs.io/en/latest/v3.0

* [[[CDM, Unidata Common Data Model]]],
Unidata: _The Common Data Model_. https://docs.unidata.ucar.edu/netcdf-java/5.0/userguide/common_data_model_overview.html

* [[[NetCDFClassic, NetCDF Classic Format]]],
Rew, R., Davis, G.: _NetCDF: An Interface for Scientific Data Access_. IEEE Computer Graphics and Applications, 10(4), 76–82 (1990). https://doi.org/10.1109/38.56302

* [[[CFConventions, CF Metadata Conventions]]],
CF Community: _Climate and Forecast (CF) Metadata Conventions, Version 1.10_. https://cfconventions.org/

* [[[GDAL, GDAL – Geospatial Data Abstraction Library]]],
GDAL Developers: _GDAL/OGR Version 3.8 Documentation_. Open Source Geospatial Foundation. https://gdal.org

* [[[OGCTMS, OGC Two Dimensional Tile Matrix Set]]],
Open Geospatial Consortium: _OGC Two Dimensional Tile Matrix Set and Tile Pyramid_ (OGC 17-083r2). https://docs.ogc.org/is/17-083r2/17-083r2.html

* [[[STAC, SpatioTemporal Asset Catalog (STAC) Specification]]],
STAC Community: _STAC Specification v1.0.0_. https://stacspec.org/en/

* [[[OGCCTPP, OGC Compliance Testing Policies and Procedures]]],
Open Geospatial Consortium: _OGC Compliance Testing Policies and Procedures_, OGC 08-134r10. https://portal.ogc.org/files/?artifact_id=55184
