name: generate

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - .gitlab-ci.yml
      - .github/workflows/create_swg_report.yml
  workflow_dispatch:

jobs:
  generate-html:
    name: Generate site with Metanorma container
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          submodules: true # ❓ Set to 'false' if submodules are not used

      # Optional: cache Fontist fonts (used by Metanorma for PDF generation)
      - uses: actions/cache@v3
        with:
          path: /root/.fontist
          key: fontist-${{ runner.os }}
          restore-keys: fontist-${{ runner.os }}

      - name: Generate site
        env:
          METANORMA_DEBUG: "1"
        run: |
          metanorma site generate --agree-to-terms

      # Optional: deploy to GitHub Pages if needed
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
