name: generate

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - .gitlab-ci.yml
      - .github/workflows/create_swg_report.yml
  workflow_dispatch:

jobs:
  test-linux:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          submodules: true

      - uses: actions/cache@v3
        with:
          path: ~/.fontist
          key: fontist-${{ runner.os }}
          restore-keys: fontist-${{ runner.os }}


      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install PlantUML + Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml graphviz
          echo "PLANTUML=/usr/share/plantuml/plantuml.jar" >> "$GITHUB_ENV"
          plantuml -version          # optional sanity check

      - uses: actions-mn/setup@v1

      # after APT has installed plantuml + graphviz + java
      - name: Expose plantuml to Metanorma
        run: |
          mkdir -p "$HOME/.local/bin"
          ln -s /usr/bin/plantuml "$HOME/.local/bin/plantuml"   # make it visible
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"             # add to PATH for all later steps

      - run: |
          which plantuml
          plantuml -version

      - name: Build site (verbose)
        env:
          METANORMA_DEBUG: "1"      # turn on Metanorma’s extended logging
        run: |
          metanorma site generate --agree-to-terms

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
